dist: xenial
sudo: required
branches:
  only:
  - master
  - "/.*/"
laguage: go
go:
  - master
install: true
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - docker version
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
after_success:
  - echo "All done!"
